// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package tutorial

import (
	"database/sql"
	"time"
)

type Post struct {
	ID        int32
	Title     string
	Content   string
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type User struct {
	ID        int32
	Name      string
	Email     string
	Age       int32
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type UserPost struct {
	ID        int32
	Title     string
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
	Name      string
	Email     string
	UserID    int32
}
